export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVER_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_USER_EVENTS = 'GET_USER_EVENTS';

export const GET_PARTICIPATING_EVENTS = 'GET_PARTICIPATING_EVENTS';
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';

export const SELECT_EVENT = 'SELECT_EVENT';
export const LOAD_SELECTED_EVENT = 'LOAD_SELECTED_EVENT';
export const CREATE_EVENT = 'GET_EVENTS';
export const DELETE_EVENT = 'DELETE_EVENT';

export const GET_VENUES = 'GET_VENUES';
export const ADD_VENUE = 'ADD_VENUE';
export const DELETE_VENUE = 'DELETE_ITEM';
export const VENUES_LOADING = 'ITEMS_LOADING';
export const SEND_VOTE = 'SEND_VOTE';

export const SET_SELECTED_VENUE = 'SET_SELECTED_VENUE';
export const SET_SELECTED_TIME = "SET_SELECTED_TIME";

export const LOAD_YELP_VENUES = 'LOAD_YELP_VENUES';
export const GET_YELP_VENUES = 'GET_YELP_VENUES';
export const REFRESH_YELP_VENUES = 'REFRESH_YELP_VENUES';

